on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: uname -a

      - name: List installed
        run: |
          sudo apt-get install aptitude
          aptitude search "~i" --display-format "%p %I" --sort installsize

      - name: Get large items
        run: sudo find / -size +30M -ls
