on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List installed
        run: |
          apt-get install aptitude
          aptitude search "~i" --display-format "%p %I" --sort installsize
