name: Testing

on:
  push:
    branches:
      - "*"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run
        run: |
          chmod +x run.sh
          ./run.sh
          sudo apt-get install aptitude
          aptitude search --sort '~installsize' --display-format '%p %I' '~i' | head

      - name: Post checkup
        run: |
          df
